### ISSUE TITLE
When will you release the code, and how long did you train the model?

### ISSUE THREAD

**Issue by lmomoy** [PJLab-ADG/LoGoNet#1]

**Comment by sankin97** [comment]
We are rushing into a new work, maybe in the next month. As for the training time for Waymo,  LoGoNet-1f needs about 30 hours with 8 A100 GPUs and 64 batch sizes and LoGoNet-5f needs about 64 hours with 8 A100 GPUs and 64 batch sizes. While about 10 hours with 4 A100 GPUs, 8 batch sizes and 80epoch for training LoGoNet on KITTI.
