### ISSUE TITLE
运行脚本时错误

### ISSUE THREAD

**Issue by Deep-Beneath** [PJLab-ADG/LoGoNet#11]
当我运行sh scripts/dist_train.sh ${NUM_GPUS} --cfg_file ${CONFIG_FILE} 出现了错误：
1.首先dist_train.sh 要接受3个参数 ：
NGPUSLIST=$1
NGPUS=$2
PY_ARGS=${@:3}
cfg_file应该传入PY_ARGS里吧，是LoGoNet-kitti.yaml文件的路径吗  第一个参数第二个参数一般填什么

2.status="$(nc -z 127.0.0.1 $PORT < /dev/null &>/dev/null; echo $?)"
    if [ "${status}" != "0" ]; then
        break;
    fi
我后来把NGPUSLIST=1 NGPUS=1直接写死，不传参了，cfg_file直接写在train.py里，后运行到上述代码一直循环，这个代码意思不是找到未占用的端口吗，如果未占用返回0吧 那么下面为啥是不等于号

**Comment by sankin97** [comment]
例如：sh scripts/dist_train.sh 0,1,2,3 4 --cfg_file ${CONFIG_FILE}
${NGPUSLIST}=0,1,2,3 指定启动的GPU，${NUM_GPUS}=4 指定启动的GPU的总数，${NGPUSLIST}序列长度等于${NUM_GPUS}
