### ISSUE TITLE
AssertionError: MMCV==1.7.1 is usebut incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### ISSUE THREAD

**Issue by iakRulan** [PJLab-ADG/LoGoNet#12]
I have a version problem when I run the training function, but these versions are not available in the repository,

`(LoG) root@ubun:/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/tools# pip install mmcv==2.1.0
ERROR: Could not find a version that satisfies the requirement mmcv==2.1.0 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.6.0, 0.6.1, 0.6.2, 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3.0, 1.3.1, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3)
ERROR: No matching distribution found for mmcv==2.1.0`

**Comment by sankin97** [comment]
We are using mmcv-full version 1.4.0. To install it, simply run the command `pip install mmcv-full==1.4.0`.  For additional information about mmcv-full, please visit the [mmcv](https://github.com/open-mmlab/mmcv/).
