### ISSUE TITLE
Question about create_waymo_database

### ISSUE THREAD

**Issue by dru9** [PJLab-ADG/LoGoNet#17]
I have one more question.
When I do,
python -m al3d_det.datasets.waymo.waymo_preprocess --cfg_file cfgs/det_dataset_cfgs/waymo_one_sweep_mm.yaml --func create_waymo_database

It make gt image file like this.
LoGoNet/detection/data/waymo/gt_database_train_sampled_1_sweep_[0,0]/segment-10017090168044687777_6380_000_6400_000_with_camera_labels_0000_Vehicle_1.png

But when I see it, it's not correct. maybe in "detection/al3d_det/datasets/waymo/waymo_preprocess.py"
gt_boxes2d[cam] = box_utils.boxes3d_to_boxes2d 
I think 196 line have a problem.
When I do this command, I have an error for saving empty array to file.

Or these patch images in gt database don't need to be correct?

**Comment by sankin97** [comment]
We train the LoGoNet without using gt_sampling. And we do not need to create the gt-database of images. This code may be put in by my collaborators. So you can comment out line191-200, line238-256, and line271-285 in [waymo_preprocess](detection/al3d_det/datasets/waymo/waymo_preprocess.py). Sorry for our negligence!

**Comment by fuzio35** [comment]
if we don't need gt_sampling,the key "use_image" in the waymo_xxx_ sweeps_mm.yaml is not uesd.So if this key doesn't been need,what is the difference between the file waymo_xxx_ sweeps_mm.yaml and waymo_xxx_ sweeps.yaml?

**Comment by fuzio35** [comment]
> We train the LoGoNet without using gt_sampling. And we do not need to create the gt-database of images. This code may be put in by my collaborators. So you can comment out line191-200, line238-256, and line271-285 in [waymo_preprocess](detection/al3d_det/datasets/waymo/waymo_preprocess.py). Sorry for our negligence!

if we don't need gt_sampling,the key "use_image" in the waymo_xxx_ sweeps_mm.yaml is not uesd.So if this key doesn't been need,what is the difference between the file waymo_xxx_ sweeps_mm.yaml and waymo_xxx_ sweeps.yaml?

**Comment by fuzio35** [comment]
> We train the LoGoNet without using gt_sampling. And we do not need to create the gt-database of images. This code may be put in by my collaborators. So you can comment out line191-200, line238-256, and line271-285 in [waymo_preprocess](detection/al3d_det/datasets/waymo/waymo_preprocess.py). Sorry for our negligence!

if we don't need gt_sampling,the key "use_image" in the waymo_xxx_ sweeps_mm.yaml is not used.So if this key doesn't been need,what is the difference between the file waymo_xxx_ sweeps_mm.yaml and waymo_xxx_ sweeps.yaml?
