### ISSUE TITLE
Visualize the results

### ISSUE THREAD

**Issue by iakRulan** [PJLab-ADG/LoGoNet#19]
Hello author, I may encounter some errors when using demo. py

`(LoG37) root@autodl-container-3b5811a6ae-c6f524b1:~/LoGoNet/detection/tools# python demo.py --cfg_file /root/LoGoNet/detection/tools/cfgs/det_model_cfgs/kitti/LoGoNet-kitti.yaml --data_path /root/LoGoNet/detection/data/kitti/testing/velodyne/000000.bin --ckpt /root/LoGoNet/detection/tools/LoGoNet-KITTI.pth
/root/miniconda3/envs/LoG37/lib/python3.7/site-packages/traits/etsconfig/etsconfig.py:428: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  % (environment_variable, parent_directory)
2023-06-05 20:51:43,504   INFO  -----------------Quick Demo of al3d-det-------------------------
2023-06-05 20:51:43,505   INFO  Total number of samples:        1
/root/miniconda3/envs/LoG37/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2023-06-05 20:51:46,868   INFO  ==> Loading parameters from checkpoint /root/LoGoNet/detection/tools/LoGoNet-KITTI.pth to CPU
2023-06-05 20:51:47,037   INFO  ==> Checkpoint trained from version: al3d_det+0.1.0+dcdb7e6+pyc3a3d92
2023-06-05 20:51:49,242   INFO  ==> Done (loaded 575/575)
2023-06-05 20:51:49,486   INFO  Visualized sample index:        1
Traceback (most recent call last):
  File "demo.py", line 110, in <module>
    main()
  File "demo.py", line 96, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/root/LoGoNet/detection/al3d_det/models/anchor_MM_kitti.py", line 86, in forward
    batch_dict = self.camera.img_backbone(batch_dict)
  File "/root/miniconda3/envs/LoG37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/LoGoNet/detection/al3d_det/models/image_modules/mmdet_ffnkitti.py", line 54, in forward
    images = batch_dict['images']
KeyError: 'images'`

-----------------
Can you tell me how to modify or update your demo. py? Thank you

**Comment by iakRulan** [comment]
![image](https://github.com/PJLab-ADG/LoGoNet/assets/88355032/f87ff316-c794-40f6-b828-6119a2a40e15)

This is an error I generated based on the source code，I hope you can tell me where the problem is, thank you！！

**Comment by bxymax** [comment]
> 
I encountered an error during my first run


File "demo.py", line 80, in main
    root_path=Path(args.data_path), ext=args.ext, logger=logger
  File "/home/bai/anaconda3/envs/logo/lib/python3.6/typing.py", line 1231, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/home/bai/anaconda3/envs/logo/lib/python3.6/typing.py", line 1186, in _generic_new
    return base_cls.__new__(cls)
TypeError: Can't instantiate abstract class DemoDataset with abstract methods get_infos_and_points, init_infos

When I add al3d_ Get in det/datasets/dataset.py_ Infos_ And_ Points, init_ After deleting the infos abstract method, the same error occurred as you:


File "demo.py", line 29, in __init__
    dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
  File "/home/bai/projects/LoGoNet-main/detection/al3d_det/datasets/dataset.py", line 34, in __init__
    self.sweep_count = self.dataset_cfg.SWEEP_COUNT
AttributeError: 'EasyDict' object has no attribute 'SWEEP_COUNT'

May I ask if your problem has been resolved? Can you tell me your solution? Thanks

**Comment by bxymax** [comment]
> File "/root/LoGoNet/detection/al3d_det/models/image_modules/mmdet_ffnkitti.



> Hello author, I may encounter some errors when using demo. py
> 
> `(LoG37) root@autodl-container-3b5811a6ae-c6f524b1:~/LoGoNet/detection/tools# python demo.py --cfg_file /root/LoGoNet/detection/tools/cfgs/det_model_cfgs/kitti/LoGoNet-kitti.yaml --data_path /root/LoGoNet/detection/data/kitti/testing/velodyne/000000.bin --ckpt /root/LoGoNet/detection/tools/LoGoNet-KITTI.pth /root/miniconda3/envs/LoG37/lib/python3.7/site-packages/traits/etsconfig/etsconfig.py:428: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp % (environment_variable, parent_directory) 2023-06-05 20:51:43,504 INFO -----------------Quick Demo of al3d-det------------------------- 2023-06-05 20:51:43,505 INFO Total number of samples: 1 /root/miniconda3/envs/LoG37/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2157.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] 2023-06-05 20:51:46,868 INFO ==> Loading parameters from checkpoint /root/LoGoNet/detection/tools/LoGoNet-KITTI.pth to CPU 2023-06-05 20:51:47,037 INFO ==> Checkpoint trained from version: al3d_det+0.1.0+dcdb7e6+pyc3a3d92 2023-06-05 20:51:49,242 INFO ==> Done (loaded 575/575) 2023-06-05 20:51:49,486 INFO Visualized sample index: 1 Traceback (most recent call last): File "demo.py", line 110, in <module> main() File "demo.py", line 96, in main pred_dicts, _ = model.forward(data_dict) File "/root/LoGoNet/detection/al3d_det/models/anchor_MM_kitti.py", line 86, in forward batch_dict = self.camera.img_backbone(batch_dict) File "/root/miniconda3/envs/LoG37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/LoGoNet/detection/al3d_det/models/image_modules/mmdet_ffnkitti.py", line 54, in forward images = batch_dict['images'] KeyError: 'images'`
> 
> Can you tell me how to modify or update your demo. py? Thank you

Hello, I also encounte the same error. And i also use KITTI dataset.Can you tell me the solution？ Thank you.

**Comment by DanielDoerr** [comment]
Hi @bxymax, Did you solve it?
If you still want to use the demo file on the Kitti dataset, you can use the dataloader as in test.py.
Replace the demo_dataset (line 78) as follows:

dist_test = False
test_set, test_loader, sampler = build_dataloader(
    dataset_cfg=cfg.DATA_CONFIG,
    class_names=cfg.CLASS_NAMES,
    batch_size=1,
    dist=dist_test, workers=4, logger=logger, training=False
)

demo_dataset = test_set
    
You also have to replace the load_data_to_gpu (line 92), otherwise the data in the forward function will not be loaded as tensors.
Use:

load_data_to_gpukitti(data_dict)

and import it from al3d_det.models

I just implemented it quickly for testing. There are certainly better ways.

**Comment by bxymax** [comment]
Thank you very much for your reply. I have already implemented visualization using third-party tools. I will also try using your method. Thank you for your help

**Comment by ziyi519** [comment]
> 非常感谢您的回复。我已经使用第三方工具实现了可视化。我也会尝试使用你的方法。谢谢你的帮助

Hello! Can you certainly explain how to visualize the results of a pkl file.You’re welcome!

**Comment by ziyi519** [comment]
> 非常感谢您的回复。我已经使用第三方工具实现了可视化。我也会尝试使用你的方法。谢谢你的帮助

Hello! Can you certainly explain how to visualize the results of a pkl file.

**Comment by hbsycym** [comment]
> Thank you very much for your reply. I have already implemented visualization using third-party tools. I will also try using your method. Thank you for your help

hello , can you tell me how to visualize the result? thanks very much
