### ISSUE TITLE
About ImageBackbone

### ISSUE THREAD

**Issue by rbldrbld** [PJLab-ADG/LoGoNet#6]
Hello! May I ask does the experiment on KITTI use the weights pre-trained on ImageNet?
https://github.com/PJLab-ADG/LoGoNet/blob/c5f14962715f31a9733dad63616e3c0af2fdce67/detection/tools/cfgs/det_model_cfgs/kitti/LoGoNet-kitti.yaml#L17

**Comment by sankin97** [comment]
Yes. You can download it from [here](https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth). If you want to train the LoGoNet, you should use it and uncomment line17.

**Comment by rbldrbld** [comment]
Thank you！
