### ISSUE TITLE
安装codecov出现错误

### ISSUE THREAD

**Issue by Gmonster-24** [PJLab-ADG/LoGoNet#7]
感谢您的开源工作，我在配置环境时在cd LoGoNet/detection/models/image_modules/swin_model && pip install -r requirements.txt 这一步出现错误：
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
我该如何解决？

**Comment by sankin97** [comment]
Just pip install codecov?
