### ISSUE TITLE
Evaluate Result precision

### ISSUE THREAD

**Issue by vehxianfish** [PJLab-ADG/LoGoNet#9]
Hi, thanks to open source excellent work. But after training, the result is not well as the paper said. The result is as follows:
![image](https://user-images.githubusercontent.com/40848953/232264572-094610c1-8966-4651-8251-13be542fb890.png)
I guess it was some fault when I installed or trained.
my environment is as follows:
```
ubuntu 18.04
pytorch=1.10.0
spconv=2.1.25
```

**Comment by vehxianfish** [comment]
Otherwise, the performance of provided training log on the validation dataset is not equal to the result in README.md. whether is an uploaded error?

**Comment by sankin97** [comment]
Please provide your training log.  We only use 2GPUs and a total batch size of 4 due to the limited data of KITTI.  The results in README are the mean AP@R40 among three difficulties for each class.

**Comment by vehxianfish** [comment]
Thanks for your quick reply. the log is in this [link](https://drive.google.com/file/d/1nTkYIsrZ7Ubhhj7NWfpuLeAy2fSdDWw_/view?usp=sharing)
We use 3 GPUs and a total batch size of 48 to validate the result quickly. But, in general, the result is better if the batch size is larger. And at least it can't be worse. So, I want to know what step is at fault.

**Comment by Marsjunwang** [comment]
Thanks for the excellent work.I also meet the performance degradtion. I  just use the weights provided in the project to evaluate the kitti val dataset,but the result is not as good as paper.The result is as fellows:
2023-05-18 12:17:58,491   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:90.5662, 89.3980, 89.0797
bev  AP:89.7979, 87.8464, 87.5922
3d   AP:88.9249, 83.4915, 78.8589
aos  AP:90.56, 89.33, 88.96
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:96.2178, 94.3393, 94.0154
bev  AP:92.9286, 90.6000, 90.0815
3d   AP:91.8647, 84.7695, 82.7189
aos  AP:96.20, 94.25, 93.86
Car AP@0.70, 0.50, 0.50:
bbox AP:90.5662, 89.3980, 89.0797
bev  AP:90.5922, 89.3992, 89.1303
3d   AP:90.5922, 89.3858, 89.1040
aos  AP:90.56, 89.33, 88.96
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:96.2178, 94.3393, 94.0154
bev  AP:96.2808, 94.4365, 94.3368
3d   AP:96.2665, 94.4014, 94.2717
aos  AP:96.20, 94.25, 93.86
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:77.3539, 73.8375, 69.4597
bev  AP:71.9948, 65.6862, 63.1394
3d   AP:67.6584, 62.8511, 58.3649
aos  AP:72.24, 68.22, 63.85
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:78.9637, 74.3189, 71.6092
bev  AP:72.2779, 66.1497, 63.1365
3d   AP:69.1400, 62.9257, 58.9703
aos  AP:73.23, 68.25, 65.21
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:77.3539, 73.8375, 69.4597
bev  AP:82.2400, 76.4459, 74.7539
3d   AP:82.2339, 76.3862, 74.7103
aos  AP:72.24, 68.22, 63.85
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:78.9637, 74.3189, 71.6092
bev  AP:83.3106, 79.2258, 76.3669
3d   AP:83.3058, 79.1496, 76.2804
aos  AP:73.23, 68.25, 65.21
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:89.5139, 82.8493, 77.1943
bev  AP:93.2137, 74.1967, 72.0911
3d   AP:87.0630, 73.2773, 70.7729
aos  AP:89.34, 82.15, 76.42
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:95.0707, 83.0192, 80.4710
bev  AP:94.5547, 76.6651, 73.5429
3d   AP:91.8386, 75.3479, 71.2423
aos  AP:94.81, 82.28, 79.58
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:89.5139, 82.8493, 77.1943
bev  AP:95.0232, 78.8821, 73.6608
3d   AP:95.0232, 78.8821, 73.6608
aos  AP:89.34, 82.15, 76.42
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:95.0707, 83.0192, 80.4710
bev  AP:95.7612, 79.0532, 76.3431
3d   AP:95.7612, 79.0532, 76.3431
aos  AP:94.81, 82.28, 79.58
[log_eval_20230518-113651.txt](https://github.com/PJLab-ADG/LoGoNet/files/11512663/log_eval_20230518-113651.txt)
I use a GPU 1060 and ubuntu 20.4

**Comment by sankin97** [comment]
> Thanks for the excellent work.I also meet the performance degradtion. I just use the weights provided in the project to evaluate the kitti val dataset,but the result is not as good as paper.The result is as fellows: 2023-05-18 12:17:58,491 INFO Car AP@0.70, 0.70, 0.70: bbox AP:90.5662, 89.3980, 89.0797 bev AP:89.7979, 87.8464, 87.5922 3d AP:88.9249, 83.4915, 78.8589 aos AP:90.56, 89.33, 88.96 Car AP_R40@0.70, 0.70, 0.70: bbox AP:96.2178, 94.3393, 94.0154 bev AP:92.9286, 90.6000, 90.0815 3d AP:91.8647, 84.7695, 82.7189 aos AP:96.20, 94.25, 93.86 Car AP@0.70, 0.50, 0.50: bbox AP:90.5662, 89.3980, 89.0797 bev AP:90.5922, 89.3992, 89.1303 3d AP:90.5922, 89.3858, 89.1040 aos AP:90.56, 89.33, 88.96 Car AP_R40@0.70, 0.50, 0.50: bbox AP:96.2178, 94.3393, 94.0154 bev AP:96.2808, 94.4365, 94.3368 3d AP:96.2665, 94.4014, 94.2717 aos AP:96.20, 94.25, 93.86 Pedestrian AP@0.50, 0.50, 0.50: bbox AP:77.3539, 73.8375, 69.4597 bev AP:71.9948, 65.6862, 63.1394 3d AP:67.6584, 62.8511, 58.3649 aos AP:72.24, 68.22, 63.85 Pedestrian AP_R40@0.50, 0.50, 0.50: bbox AP:78.9637, 74.3189, 71.6092 bev AP:72.2779, 66.1497, 63.1365 3d AP:69.1400, 62.9257, 58.9703 aos AP:73.23, 68.25, 65.21 Pedestrian AP@0.50, 0.25, 0.25: bbox AP:77.3539, 73.8375, 69.4597 bev AP:82.2400, 76.4459, 74.7539 3d AP:82.2339, 76.3862, 74.7103 aos AP:72.24, 68.22, 63.85 Pedestrian AP_R40@0.50, 0.25, 0.25: bbox AP:78.9637, 74.3189, 71.6092 bev AP:83.3106, 79.2258, 76.3669 3d AP:83.3058, 79.1496, 76.2804 aos AP:73.23, 68.25, 65.21 Cyclist AP@0.50, 0.50, 0.50: bbox AP:89.5139, 82.8493, 77.1943 bev AP:93.2137, 74.1967, 72.0911 3d AP:87.0630, 73.2773, 70.7729 aos AP:89.34, 82.15, 76.42 Cyclist AP_R40@0.50, 0.50, 0.50: bbox AP:95.0707, 83.0192, 80.4710 bev AP:94.5547, 76.6651, 73.5429 3d AP:91.8386, 75.3479, 71.2423 aos AP:94.81, 82.28, 79.58 Cyclist AP@0.50, 0.25, 0.25: bbox AP:89.5139, 82.8493, 77.1943 bev AP:95.0232, 78.8821, 73.6608 3d AP:95.0232, 78.8821, 73.6608 aos AP:89.34, 82.15, 76.42 Cyclist AP_R40@0.50, 0.25, 0.25: bbox AP:95.0707, 83.0192, 80.4710 bev AP:95.7612, 79.0532, 76.3431 3d AP:95.7612, 79.0532, 76.3431 aos AP:94.81, 82.28, 79.58 [log_eval_20230518-113651.txt](https://github.com/PJLab-ADG/LoGoNet/files/11512663/log_eval_20230518-113651.txt) I use a GPU 1060 and ubuntu 20.4

This issue may be caused by a specific code line located at [line](https://github.com/PJLab-ADG/LoGoNet/blob/efd894a2825072959beae26c887cd4073d225fe2/detection/al3d_det/datasets/kitti/kitti_dataset.py#L119). To ensure consistency with the model training, we have made updates and are now using cv2.

**Comment by Marsjunwang** [comment]
Thanks for your reply. Now i am sure the skimage.io.imread is different from the cv2.imread.The link you provided maybe need to include the skio.imread in the get_image() funtion not just get_image_shape() function. Thank you for you quick reply again.The new evaluation log is as fellows for anyone who may need:
[log_eval_20230604-084754.txt](https://github.com/PJLab-ADG/LoGoNet/files/11645251/log_eval_20230604-084754.txt)

**Comment by russellyq** [comment]
Hi @sankin97 ,

this line (https://github.com/PJLab-ADG/LoGoNet/blob/efd894a2825072959beae26c887cd4073d225fe2/detection/al3d_det/datasets/kitti/kitti_dataset.py#L119) is still "skio.imread". Have you updated to cv2 ?

**Comment by KuMyy** [comment]
Hi @sankin97 
I used 4 GPUs to train the kitti dataset model, with a batch_size of 2 for each GPU, but the accuracy is lower than your result, as shown below.
Car AP@0.70, 0.70, 0.70:
bbox AP:90.6945, 89.5647, 89.3071
bev  AP:89.9241, 88.0963, 87.7424
3d   AP:89.1805, 79.0104, 78.4840
aos  AP:90.68, 89.43, 89.11
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:96.3647, 94.6181, 92.4479
bev  AP:93.0533, 90.8921, 88.8275
3d   AP:92.0431, 82.7483, 80.4445
aos  AP:96.33, 94.44, 92.22
Car AP@0.70, 0.50, 0.50:
bbox AP:90.6945, 89.5647, 89.3071
bev  AP:90.6680, 89.5867, 89.3912
3d   AP:90.6680, 89.5660, 89.3515
aos  AP:90.68, 89.43, 89.11
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:96.3647, 94.6181, 92.4479
bev  AP:96.4016, 94.8079, 94.6910
3d   AP:96.3752, 94.7462, 94.5643
aos  AP:96.33, 94.44, 92.22
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:76.3487, 73.0537, 68.0181
bev  AP:70.0796, 63.4617, 60.7128
3d   AP:65.4710, 59.6043, 54.6021
aos  AP:71.72, 67.76, 62.72
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:77.7554, 73.8310, 69.8063
bev  AP:70.3274, 63.4872, 59.0441
3d   AP:66.3791, 58.4017, 52.9572
aos  AP:72.52, 68.04, 63.68
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:76.3487, 73.0537, 68.0181
bev  AP:82.2021, 75.8938, 73.7390
3d   AP:82.1562, 75.8171, 73.6392
aos  AP:71.72, 67.76, 62.72
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:77.7554, 73.8310, 69.8063
bev  AP:83.4067, 78.4574, 74.9873
3d   AP:83.3610, 78.3173, 74.8186
aos  AP:72.52, 68.04, 63.68
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:93.3719, 82.6419, 80.5885
bev  AP:85.6401, 74.9306, 70.2753
3d   AP:84.5666, 69.5697, 67.7682
aos  AP:93.26, 82.14, 80.10
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:95.4149, 84.7896, 82.0532
bev  AP:89.9754, 75.1572, 72.1419
3d   AP:86.7094, 71.5223, 68.4993
aos  AP:95.30, 84.27, 81.52
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:93.3719, 82.6419, 80.5885
bev  AP:91.2515, 78.0292, 75.8237
3d   AP:91.2515, 78.0292, 75.8237
aos  AP:93.26, 82.14, 80.10
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:95.4149, 84.7896, 82.0532
bev  AP:93.3445, 79.6764, 76.8671
3d   AP:93.3445, 79.6764, 76.8671
aos  AP:95.30, 84.27, 81.52
 I saw in your reply that line 119 of kitti_dataset.py should be changed to cv2, but your code has not been updated. Do I need to make the change? My training log is here

[log_train_20250210-161715.txt](https://github.com/user-attachments/files/18762088/log_train_20250210-161715.txt)

**Comment by fuzio35** [comment]
> Hi [@sankin97](https://github.com/sankin97) I used 4 GPUs to train the kitti dataset model, with a batch_size of 2 for each GPU, but the accuracy is lower than your result, as shown below. Car AP@0.70, 0.70, 0.70: bbox AP:90.6945, 89.5647, 89.3071 bev AP:89.9241, 88.0963, 87.7424 3d AP:89.1805, 79.0104, 78.4840 aos AP:90.68, 89.43, 89.11 Car AP_R40@0.70, 0.70, 0.70: bbox AP:96.3647, 94.6181, 92.4479 bev AP:93.0533, 90.8921, 88.8275 3d AP:92.0431, 82.7483, 80.4445 aos AP:96.33, 94.44, 92.22 Car AP@0.70, 0.50, 0.50: bbox AP:90.6945, 89.5647, 89.3071 bev AP:90.6680, 89.5867, 89.3912 3d AP:90.6680, 89.5660, 89.3515 aos AP:90.68, 89.43, 89.11 Car AP_R40@0.70, 0.50, 0.50: bbox AP:96.3647, 94.6181, 92.4479 bev AP:96.4016, 94.8079, 94.6910 3d AP:96.3752, 94.7462, 94.5643 aos AP:96.33, 94.44, 92.22 Pedestrian AP@0.50, 0.50, 0.50: bbox AP:76.3487, 73.0537, 68.0181 bev AP:70.0796, 63.4617, 60.7128 3d AP:65.4710, 59.6043, 54.6021 aos AP:71.72, 67.76, 62.72 Pedestrian AP_R40@0.50, 0.50, 0.50: bbox AP:77.7554, 73.8310, 69.8063 bev AP:70.3274, 63.4872, 59.0441 3d AP:66.3791, 58.4017, 52.9572 aos AP:72.52, 68.04, 63.68 Pedestrian AP@0.50, 0.25, 0.25: bbox AP:76.3487, 73.0537, 68.0181 bev AP:82.2021, 75.8938, 73.7390 3d AP:82.1562, 75.8171, 73.6392 aos AP:71.72, 67.76, 62.72 Pedestrian AP_R40@0.50, 0.25, 0.25: bbox AP:77.7554, 73.8310, 69.8063 bev AP:83.4067, 78.4574, 74.9873 3d AP:83.3610, 78.3173, 74.8186 aos AP:72.52, 68.04, 63.68 Cyclist AP@0.50, 0.50, 0.50: bbox AP:93.3719, 82.6419, 80.5885 bev AP:85.6401, 74.9306, 70.2753 3d AP:84.5666, 69.5697, 67.7682 aos AP:93.26, 82.14, 80.10 Cyclist AP_R40@0.50, 0.50, 0.50: bbox AP:95.4149, 84.7896, 82.0532 bev AP:89.9754, 75.1572, 72.1419 3d AP:86.7094, 71.5223, 68.4993 aos AP:95.30, 84.27, 81.52 Cyclist AP@0.50, 0.25, 0.25: bbox AP:93.3719, 82.6419, 80.5885 bev AP:91.2515, 78.0292, 75.8237 3d AP:91.2515, 78.0292, 75.8237 aos AP:93.26, 82.14, 80.10 Cyclist AP_R40@0.50, 0.25, 0.25: bbox AP:95.4149, 84.7896, 82.0532 bev AP:93.3445, 79.6764, 76.8671 3d AP:93.3445, 79.6764, 76.8671 aos AP:95.30, 84.27, 81.52 I saw in your reply that line 119 of kitti_dataset.py should be changed to cv2, but your code has not been updated. Do I need to make the change? My training log is here
> 
> [log_train_20250210-161715.txt](https://github.com/user-attachments/files/18762088/log_train_20250210-161715.txt)

hello，did you has the result of Waymo？in my device，all metric of waymo is zero，but kitti dosen‘t.
